# Global settings applied to the whole site.
[build]
  command = "./buildClient.sh"
  publish = "./build"

[context.production.environment]
  REGION = "eu-west-1"
  API_URL = "https://qqh3tvpcq7.execute-api.eu-west-1.amazonaws.com/prod/api"
  USER_POOL_ID = "eu-west-1_lqothH8kU"
  APP_CLIENT_ID = "1f07842jq1c3ah789ase0ucro2"

[context.sit.environment]
  REGION = "eu-west-1"
  API_URL = "https://ci08thnyaj.execute-api.eu-west-1.amazonaws.com/sit/api"
  USER_POOL_ID = "eu-west-1_lGUbdNBYr"
  APP_CLIENT_ID = "3ignt6jg8stp7njq0tm1hk0li3"
