export default {
  apiGateway: {
    REGION: "REGION_PLACEHOLDER",
    URL: "API_URL_PLACEHOLDER"
  },
  cognito: {
    REGION: "REGION_PLACEHOLDER",
    USER_POOL_ID: "USER_POOL_ID_PLACEHOLDER",
    APP_CLIENT_ID: "APP_CLIENT_ID_PLACEHOLDER",
    IDENTITY_POOL_ID: "IDENTITY_POOL_ID_PLACEHOLDER"
  }
};
